name: Linux Application
description: Flutter Integration with RHEL and FireBase
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  http: ^0.12.2
flutter:
  uses-material-design: true
